export const ACTIONS = {
    SET_ACTIVE_STEP: "SET_ACTIVE_STEP",
    SET_PRODUCTS: 'SET_PRODUCTS',
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",
    CHANGE_VARIANT: "CHANGE_VARIANT",
    SAVE_PRODUCT: "SAVE_PRODUCT",
    RESTORE_PRODUCT: "RESTORE_PRODUCT",
    SET_COLOR: "SET_COLOR",
};